
@extends('layout')

@section('content')


<div class="card">
        <h1 class="text-uppercase text-center v-b-font">Regulamin</h1>
        <div class="card-body">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur temporibus nesciunt consequuntur magni facilis eaque consectetur omnis repudiandae iure, officiis dolores eius alias aut a molestiae maiores laboriosam natus quod?
            Nemo veritatis optio odio laudantium nulla aliquid qui velit? Qui animi dolor, libero ipsa quas sapiente eius iste eum amet tenetur sunt dolores laudantium, ipsum veritatis autem ratione minima laborum?
            Mollitia tempore blanditiis at tempora rem doloribus maxime vitae veritatis nihil ex, quasi quis ratione voluptates voluptate molestias saepe ullam expedita suscipit dicta perspiciatis corporis incidunt? Asperiores dolore nemo iste?
            Mollitia deserunt omnis accusantium esse numquam dicta quam, voluptas officiis nemo architecto exercitationem, sequi cumque eaque consequatur dolor veniam dolorum dignissimos voluptatum libero rerum animi. Ut porro ad et suscipit!
            Itaque porro quia nisi nostrum perferendis, quaerat, nulla quod, ab voluptatibus nemo culpa eos consequatur. Assumenda, dolorum ipsam. Sapiente quisquam omnis assumenda perspiciatis aspernatur fugiat laudantium similique temporibus doloribus quibusdam.
            Facere, nisi dolore? Vero odit, cum quas quos omnis aut sunt reiciendis tempore alias delectus reprehenderit laudantium illum quibusdam nisi magni ex dicta numquam dolore sequi molestiae assumenda mollitia placeat.
            Dolore aut in exercitationem harum quaerat voluptatem, eum, officiis odio eos molestiae pariatur dignissimos recusandae quas. Repudiandae, quis sequi! Nisi a eius sit pariatur esse quidem inventore non, provident consequatur.
            Velit totam dolorum ipsam! Placeat rem accusamus doloremque odio mollitia similique blanditiis illo. Hic earum accusamus modi. Vitae iusto unde quis qui, consequatur molestiae pariatur totam, ad perspiciatis ex laborum.
            Ratione itaque tempore id fugit nam ipsum minima architecto. Maiores, facere tenetur repellendus beatae ut reprehenderit laborum, quo distinctio vitae sunt quasi nobis, nam delectus repellat voluptates at culpa architecto.
            Accusamus sequi, nisi similique officiis ipsam quasi provident, consequuntur itaque eos quod deleniti dolorem eaque, sunt necessitatibus optio dolore sed dolor consectetur adipisci? Obcaecati quae adipisci, consectetur commodi optio error?
            Nulla minima vel eaque nemo hic quis iusto quaerat doloribus impedit veritatis! Sunt, saepe perspiciatis quas id dolore quasi quis ipsam sint quidem magnam! Hic assumenda obcaecati voluptatem odit. Mollitia.
            Quia dolores ipsa nulla consequuntur, animi dolorem voluptates aspernatur. Maiores assumenda velit excepturi, molestiae mollitia delectus rem error iure ab possimus, ducimus voluptates nostrum aliquid. Libero facere consequatur fugit deleniti!
            Esse et facilis alias illo nemo neque, at voluptas eos consectetur quos nesciunt! Exercitationem corrupti sed rerum sit debitis fugit quisquam, est animi? Voluptate totam tenetur esse? Necessitatibus, rem placeat.
            Sequi incidunt ea aliquid reiciendis, repellat repudiandae? Ipsam dolorum cum, quas saepe accusantium asperiores totam sunt autem temporibus, officiis nihil ipsa dolor? Quod repudiandae soluta optio officiis quos dignissimos. Facilis?
            Perspiciatis consectetur pariatur laboriosam culpa ipsa autem accusantium modi reiciendis voluptates eum animi cupiditate iure excepturi, in dolorum, minima deleniti. Aliquam beatae natus sapiente perferendis ratione ipsum error cumque assumenda.
            Veniam eum placeat necessitatibus nihil libero, eaque ullam a pariatur dolorem facere at quasi blanditiis iure, repudiandae quis, odio unde. Distinctio eveniet explicabo dolore mollitia deleniti quibusdam animi aut facilis.
            Voluptatum architecto aut fugiat sequi cupiditate officia odit ex enim nisi esse perferendis reprehenderit atque nulla tenetur quasi est possimus voluptate quibusdam natus, quaerat harum, veniam iure eum? A, vero.
            Odio nemo, perspiciatis et, eligendi consequuntur fugiat atque voluptatem ea impedit modi quod repellat inventore in veniam nulla, saepe sint temporibus fuga. Repellat quibusdam architecto minus vel nulla veniam provident!
            Animi blanditiis dolorem sit asperiores quaerat quam quo. Optio modi placeat quam velit vel recusandae, saepe ducimus numquam delectus voluptatem veritatis sed vero, sunt quis maxime a perspiciatis facere provident!
            Aut et voluptates deserunt cum ipsum eveniet iure cumque sit nobis officia soluta, molestias harum ab repellendus dicta, officiis, culpa eum nihil eaque laudantium. Asperiores sunt exercitationem fuga iure nostrum.
            Corrupti recusandae, natus nam hic dicta dolores quam, blanditiis placeat velit vero est quisquam aliquid accusantium enim similique accusamus quas harum. Minus vero fugiat cumque odit nobis a hic repudiandae?
            Unde, minima sapiente deserunt consequatur nobis laudantium amet facilis quo sequi ipsum dolorum velit officiis! Fugit, vero quasi. Quae animi doloribus assumenda, atque vitae culpa nam eligendi reprehenderit fugiat recusandae.
            Perspiciatis ut neque dolorum. Tempore nisi aperiam reiciendis iste. Perferendis, reiciendis! Nulla earum minima vitae aliquid veritatis, harum, eos modi repudiandae nemo est accusantium possimus facilis totam alias, magni non?
            Ipsum vero eligendi cum! Labore quidem, sed ea velit quasi id aspernatur veniam in. Quia in tempore vero dolorum aspernatur rerum! Repudiandae odio blanditiis omnis quaerat ad eligendi. Distinctio, repudiandae?
            Velit, illo esse? Quod odit neque exercitationem temporibus officia molestiae nesciunt incidunt a ex facere perspiciatis vitae et omnis sit similique aspernatur, assumenda reiciendis, explicabo quidem error quos. Nostrum, tempore.
            Tenetur tempore illo laboriosam quo est accusantium repellendus magnam suscipit tempora, ut repellat praesentium rerum doloremque vel error, consectetur eum, aperiam eius maxime nesciunt consequuntur similique voluptate blanditiis amet. Id.
            Cupiditate sit, at quisquam corporis id reprehenderit, eius molestiae nesciunt animi perspiciatis enim? Dolorum velit blanditiis iure, enim quasi sapiente ab accusamus, perspiciatis, laborum ex iusto ducimus dolore possimus architecto.
            Officia, dolores unde perspiciatis ipsam corporis esse molestiae accusamus, itaque illo non facilis atque sequi rerum eos recusandae. Animi voluptate, quas labore dolores aspernatur hic libero expedita ipsam omnis beatae!
            Molestiae rem pariatur iure amet id, unde at repellat ipsam laboriosam expedita perferendis quo assumenda. Qui sit reiciendis molestiae molestias, voluptate labore id laudantium aperiam architecto voluptas similique atque distinctio?
            Labore iure autem dolore dolorum ullam ipsa possimus et placeat quibusdam vero cupiditate, ducimus, ea voluptatum dicta illum eveniet harum accusamus, id vel debitis accusantium nobis doloribus esse? Distinctio, illo.
            Tenetur odit magnam ea dolor corrupti vero repellat illo voluptas natus! Nisi temporibus eos, tempore quo aliquid accusamus. Asperiores sequi ducimus eos eius. Natus corporis vitae mollitia, impedit nisi quasi?
            Odit esse ratione expedita quae eius necessitatibus exercitationem vitae, fuga reiciendis fugit commodi consectetur. Ea repudiandae facilis ex enim dignissimos temporibus tenetur, iste, odit vel nesciunt eligendi, in fuga delectus!
            Alias sunt aut, quia adipisci placeat iure iste fugiat, quisquam voluptate autem excepturi necessitatibus nobis doloribus? Voluptas itaque, alias vero, consequuntur dignissimos dolorem, earum delectus veniam dolor quibusdam voluptatibus eius.
            Odit repellat officia at labore asperiores obcaecati numquam rerum modi, totam fuga provident laborum saepe! Facere possimus impedit aperiam fugit iste earum laudantium delectus! Non expedita minima quia architecto qui!
            Ut consectetur, tempora nemo architecto suscipit explicabo recusandae placeat odit odio ducimus ex quae quis dicta illum voluptatum ullam molestiae mollitia non? Modi blanditiis, explicabo suscipit voluptatibus perferendis obcaecati. Aperiam.
            Quam repudiandae mollitia eligendi, fugiat dolore praesentium quod hic, eveniet amet ea quisquam eos a beatae deserunt cum sequi omnis, at laboriosam! Sit sunt aspernatur laboriosam doloremque neque natus culpa.
            Nulla nobis fugiat, aperiam debitis commodi maiores neque. Nesciunt a qui provident perferendis commodi quaerat modi ex doloremque, unde pariatur obcaecati quis, ea minima maxime. Accusantium consequatur neque deserunt omnis.
            Recusandae hic nam quis in tempora inventore sit voluptas aliquam minus quia aut ut laborum pariatur numquam soluta cum vitae doloremque incidunt nesciunt dolorem ipsam labore saepe, temporibus odio. Et.
            Officiis cupiditate laboriosam quisquam et aut velit nisi inventore consequatur fugit voluptas, numquam, expedita consectetur non dolorum minima a ab illum hic ratione. Maiores eaque, omnis alias itaque voluptate dignissimos!
            Asperiores libero sit ducimus hic quisquam quibusdam. Id commodi dolor eos consequuntur quasi, laboriosam ullam illum autem neque officiis beatae maxime! Asperiores et magnam in, consequatur ad ducimus voluptatem ipsa!
            Rerum sed ipsa dicta fugiat aperiam doloribus corrupti veritatis blanditiis beatae omnis, repellendus voluptas neque deleniti vel animi ipsam exercitationem praesentium quos debitis dignissimos nulla! Sequi, odio ex. In, molestiae!
            Sit consequatur odio iste maiores porro quasi? Soluta enim esse asperiores. Impedit, rem deleniti blanditiis expedita voluptates dolorem molestiae labore ad ullam nesciunt at ipsam necessitatibus? Quidem qui asperiores iure.
            Autem mollitia odio dolorem. Pariatur, laboriosam autem illo vero soluta veritatis aperiam recusandae impedit et! Nemo mollitia distinctio repellendus consequuntur quia provident, asperiores exercitationem totam maiores aspernatur sit animi eos?
            Error nobis similique qui magnam expedita voluptatem corporis quaerat dignissimos itaque earum, iure consectetur! Ad deserunt facilis mollitia iure, aut provident ullam accusamus non ab magni nihil vitae laborum vero.
            Odio fuga omnis quam modi architecto cupiditate blanditiis adipisci dicta, commodi vero eveniet! Officiis, distinctio cumque modi, incidunt perspiciatis tempora iure aut sed vitae quia enim accusamus alias, quibusdam laudantium?
            Architecto ullam facere facilis unde voluptatem deleniti distinctio adipisci ratione corporis in dolor sunt beatae hic laudantium doloremque accusantium illo, laborum vel sed voluptatum eum aperiam molestiae eos? Libero, architecto!
            Rem quaerat quas similique reprehenderit. Maiores quae repellat possimus praesentium nemo voluptatem consequuntur cum vel obcaecati? Aliquid est reiciendis aut eveniet modi dolores sequi, laborum numquam corrupti accusantium incidunt architecto.
            Ipsum ex praesentium aliquid assumenda repellendus ipsa tempore in consequuntur. Quia excepturi ipsa adipisci fugit hic cupiditate, corporis dolor, quo ipsum deleniti doloremque veritatis numquam ut labore sequi repellat odio?
            Inventore quam autem est doloremque aut minima neque asperiores, necessitatibus, nesciunt veritatis aliquid ea, dolores dignissimos quis voluptatem. Repellat, corporis. Expedita nihil repudiandae natus ullam voluptatum architecto omnis saepe nam!
            Ipsam aspernatur perspiciatis repellendus voluptas provident quo? Nihil qui ducimus sequi, harum repudiandae molestias nobis eum perferendis iste quis molestiae architecto ipsum quibusdam? Minus alias explicabo veritatis ducimus at consequatur!
            Enim quibusdam hic assumenda voluptas explicabo provident illo minima quae. Officia laboriosam dolorem dicta soluta vero rem corrupti maxime eius consequatur odit temporibus distinctio, qui deserunt commodi. Deserunt, minus enim?
            Consequuntur praesentium assumenda ipsum a. Exercitationem distinctio ex numquam voluptate, hic tempora aliquam quia debitis, quibusdam ad blanditiis laudantium tempore dolores cupiditate ut aspernatur dolorum? Laudantium pariatur adipisci sint doloribus.
            Nobis accusamus repudiandae sint aliquid doloremque, incidunt quod commodi laudantium suscipit accusantium velit? Nostrum nobis iusto architecto dolores quo dicta ab, nihil alias repellat et amet saepe consequuntur velit assumenda.
            Officiis nihil, doloribus labore fugiat qui ducimus, animi id nostrum nisi illum voluptatem natus ab assumenda consequuntur iste fuga tempora sapiente sequi deserunt. Explicabo tenetur veritatis, voluptates repellendus placeat perferendis.
            Accusamus, ipsum quam! Perferendis nihil adipisci sit facilis tempora expedita fuga natus nisi corrupti mollitia numquam quod, fugiat perspiciatis velit earum aspernatur similique laboriosam repellendus culpa et porro. Enim, ex!
            Velit earum illum voluptatum labore, nemo repellendus optio quasi saepe neque? Hic, quis quae. Reprehenderit optio eaque deserunt iure perferendis neque, repellat quasi nulla quam, magni possimus quos? Excepturi, incidunt!
            A fuga harum delectus pariatur impedit magni earum debitis. Sunt nobis exercitationem ab cumque officia eveniet eligendi velit nisi rem et. Incidunt dicta voluptatum ratione aperiam a animi aliquam reprehenderit.
            Sed blanditiis nostrum minima officia beatae culpa. Nulla numquam qui dignissimos ipsa esse dolore asperiores odit repellendus illum quam ut dolorem sapiente cumque hic repudiandae, ab eos voluptate totam. Temporibus.
            Ab nam vitae corrupti. Et placeat modi illum, adipisci dolore ad quo, in at, dolorem laboriosam quia alias. Asperiores doloribus corporis reprehenderit sequi in et debitis veritatis quod, aspernatur repellat?
            Eius mollitia architecto neque molestiae odio libero molestias quia eligendi expedita sed dolor ad assumenda optio amet perspiciatis praesentium, accusantium similique exercitationem? Aspernatur eos, atque possimus doloribus rerum unde quaerat.
            Quae, dolore amet voluptates sequi eligendi repudiandae. Consequuntur nostrum earum ad, obcaecati at, labore molestias fugiat totam ipsam fugit dolore eaque quis aliquid nulla, distinctio blanditiis. Iste sunt quod perspiciatis.
            Tenetur quidem voluptas quisquam fugiat aliquam sequi illo ad vitae nostrum. Ad, dolorem dolores quia, ab asperiores aut, velit dolorum quae facere dignissimos unde maxime commodi nam soluta voluptas voluptatem.
            Optio dolorum consequuntur in qui. Vero ex consequuntur eos minima veritatis dolorum quidem voluptates labore non autem dolore fuga necessitatibus suscipit ratione officia nulla rem quae facere aliquam, assumenda possimus?
            Nisi perferendis dolorem sunt, nulla qui est ducimus minima cum molestias enim, quidem fugit officiis, totam nam debitis sit? Provident velit repellat delectus ad quo numquam voluptates quae esse quam.
            Rerum culpa officiis sit eligendi atque nihil quia impedit nostrum nam ea soluta quis molestiae enim repellat ex, veniam ipsam recusandae sunt, hic dicta necessitatibus dolor! Cupiditate voluptatibus consequuntur voluptatum!
            Ipsam animi atque mollitia id dolorem amet rerum deserunt corporis explicabo quidem facere accusantium obcaecati, quas nihil eveniet tempore, laudantium quod, minus ex? Dicta totam nisi recusandae culpa hic placeat.
            Accusamus, expedita iusto. Iure quisquam ullam odio labore in? Illo fugit odit odio explicabo eos recusandae tempore exercitationem suscipit error? Aliquid animi culpa veritatis, repudiandae at odit. Praesentium, non similique?
            Distinctio accusantium quasi qui aliquid autem deserunt praesentium culpa blanditiis, quaerat dignissimos, iure voluptatibus aspernatur laborum voluptatem quisquam beatae consequuntur? A cum quaerat corrupti eveniet alias dicta nobis, delectus autem.
            Enim quos placeat nemo dolor fugiat, reiciendis eos officia autem sint debitis ad atque veritatis non nostrum odio ea repellat explicabo. Doloremque beatae reiciendis asperiores labore culpa quod quisquam quis!
            Aut fugit quia minima tenetur, recusandae eum mollitia ut nam? Consequuntur laborum neque nam cumque nobis beatae, eveniet tenetur praesentium nulla magnam sunt libero quae voluptates officiis soluta. Officiis, architecto.
            A modi odio cumque fuga dolor saepe sunt porro voluptas nisi, magnam quia dolores harum fugit sit magni ullam facilis! Blanditiis aspernatur reiciendis maiores, reprehenderit omnis adipisci labore quae error.
            Ut totam in, omnis modi suscipit corporis adipisci obcaecati sit nam, illum dicta ipsa consequuntur! Corrupti eveniet, dolores quis quos modi hic incidunt quo inventore repudiandae, officia rem exercitationem minima!
            Obcaecati nobis, voluptatum dolore labore quas ab ea enim facilis. Laudantium necessitatibus deleniti nesciunt dolorum commodi iste temporibus quia, soluta adipisci pariatur culpa laborum fugiat odit rerum explicabo nulla iure?
            Vel ab beatae excepturi veniam. Veniam praesentium ipsam totam illum consequuntur mollitia laudantium non aperiam repellendus, ullam nihil tenetur, ducimus eaque minima quo laboriosam quos. Quae labore placeat laborum numquam?
            Quod, illo excepturi a aliquam perspiciatis, ab voluptates expedita et doloremque quia adipisci maiores nihil ipsam quidem aliquid. Porro minima, voluptas unde veniam facere quia maxime recusandae quisquam quae aliquam.
            Quidem, cumque libero enim quas quos perferendis nam earum ad a facilis amet tenetur magni vero provident, pariatur nihil delectus, alias ullam? Fugiat corporis consequatur quis vero perferendis, neque eaque.
            Ipsam rem impedit dolorum consectetur. Unde nobis, assumenda similique sequi ipsam laboriosam quis corporis est aut et quo, adipisci, vel molestiae animi aperiam nesciunt? Unde voluptate commodi nemo maxime neque?
            Consequuntur repellat, quibusdam ullam eligendi numquam corporis libero. Expedita eius laboriosam illo, iure minus, eaque at adipisci quae nulla perferendis dignissimos aut sequi vero sit natus quia ipsa dolores voluptate.
            Enim, tenetur deleniti saepe doloremque aliquam excepturi ullam consequuntur, ratione debitis exercitationem obcaecati laboriosam odio unde sint explicabo non perspiciatis labore fugit repellat, dolor modi provident facilis suscipit. Adipisci, consequuntur!
            Accusantium, minima. Dignissimos esse voluptatem placeat quia cum ut laboriosam pariatur excepturi aperiam, accusantium recusandae sunt labore assumenda magni unde optio repellendus earum? Facere ut explicabo deserunt eos consequuntur quas?
            Rerum dignissimos nam, magnam suscipit voluptatibus consectetur eius tempore, nostrum nisi incidunt illo possimus. Magnam id sit corporis? Quis voluptatibus dolores vel ut excepturi sapiente dolor totam cum obcaecati iure!
            Sequi laborum velit, inventore repudiandae nobis voluptatem modi dicta vitae error facilis placeat mollitia harum et ad rem ab tempora nulla tenetur alias, earum possimus ipsum, nisi omnis ipsam. In!
            Amet quod asperiores doloremque dolores accusantium voluptatibus fugit? Veritatis fugiat perferendis ipsam amet harum consequatur illum nemo consequuntur doloremque similique voluptate possimus temporibus at obcaecati sit, accusamus cupiditate ratione. Officiis!
            Fugiat sunt, tenetur rerum aspernatur nam iste ab eaque deserunt consequatur, optio tempore? Mollitia, eum. Optio vitae dicta voluptatum error! Quas officiis temporibus beatae, a minus inventore laboriosam perferendis libero.
            Molestiae deleniti nam odio architecto voluptate aspernatur dolor, veritatis sapiente minus enim assumenda nemo sed repellat qui labore doloremque necessitatibus possimus. Distinctio ab esse in provident cupiditate omnis dolorum a!
            Placeat iusto quod reiciendis odio unde laborum nemo vero dolorem adipisci molestiae quam, repellendus quis tempora qui autem. Iusto dolorem delectus deleniti possimus porro saepe quae labore unde obcaecati laudantium.
            Illum facere doloremque repudiandae eligendi. Expedita temporibus repudiandae accusantium impedit officia quisquam nam voluptas delectus illum harum, suscipit neque qui ratione quam doloribus porro unde corporis consectetur. Modi, laudantium corrupti.
            Ut veniam incidunt consequuntur dicta! Veniam velit veritatis laborum sint error, totam, numquam quod quis dignissimos alias voluptate sit labore quisquam! Fugiat nostrum nihil sed vero quod. Consectetur, earum minus.
            Dolorum aut neque exercitationem minus quae accusantium sequi architecto ab. Provident nihil laboriosam ducimus perspiciatis repellendus est. Quis, mollitia? Laboriosam eaque tempore magni voluptatem odit numquam totam repellat, velit cumque.
            Odio soluta excepturi numquam, rerum aliquam pariatur, ipsum quidem blanditiis voluptas suscipit assumenda cupiditate autem consectetur accusamus amet ad corporis neque, sed nam officia. Necessitatibus doloribus distinctio similique assumenda delectus.
            Nemo soluta obcaecati unde adipisci modi beatae illum dolorem et in nam, ex natus voluptas iste numquam ipsum impedit ratione nisi quas sequi? Minus provident rem porro, quae eos nemo!
            Earum temporibus suscipit, laudantium vel omnis similique et doloribus commodi. Atque, obcaecati sit? Perspiciatis dolorem rerum ad quaerat consequuntur nesciunt repellendus, aut officia commodi voluptatum adipisci facilis ullam possimus consequatur!
            Reiciendis enim aut pariatur at? Magni rem illo quod ut modi aliquam perspiciatis magnam, hic beatae doloribus mollitia reprehenderit necessitatibus non molestias! Aliquam quod atque, numquam ut dignissimos eos minima.
            Odit saepe debitis id, beatae magnam blanditiis sint architecto obcaecati fugit vitae, quidem soluta et quis aliquid pariatur! Vel id eveniet dolorem nulla! Odio neque incidunt totam quia, fugit laboriosam.
            Voluptas itaque ullam adipisci modi expedita provident ea, repudiandae quisquam exercitationem ab incidunt, quae blanditiis. Sequi modi tenetur distinctio atque, nemo nesciunt dolorem repudiandae perferendis maxime est voluptatum? Qui, delectus!
            Eius saepe minus fugiat, voluptas quis voluptatum ratione magni eos obcaecati consequuntur voluptatem sunt ullam nobis nihil doloremque? Ipsum dolorem odit eos excepturi eligendi facere voluptatum consequatur quia vitae distinctio.
            Rerum ea molestiae molestias recusandae aliquid unde magni. Iusto ratione, omnis culpa ut, nemo nisi amet qui facilis cumque ex eum ad odio deserunt. Ipsa reprehenderit odio repudiandae tenetur eveniet?
            Impedit, rem doloremque! Adipisci voluptates cum itaque eum molestias hic rem laborum molestiae repellat magni iusto praesentium architecto aperiam placeat, ut nihil, voluptas sunt impedit? Dolorem, iste. Autem, adipisci ex.
            Perferendis libero laboriosam vel rerum odit adipisci, esse impedit, molestiae fuga facere neque recusandae sapiente odio labore id deleniti. Temporibus dolorum tenetur dicta sequi magnam optio nemo necessitatibus soluta aliquam.
            Eligendi, aliquam reiciendis. Voluptatibus optio praesentium quaerat a magni, consequatur distinctio ut voluptatum enim, nesciunt expedita repudiandae, nobis iusto nulla omnis maiores fugiat itaque similique adipisci. Reprehenderit consequuntur excepturi consequatur?
        </div>
</div>


@endsection